### REGISTRATION
POST http://localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "Odilbek",
  "surname": "Abdullayev",
  "phone": "998994245558",
  "login": "admin",
  "password": "admin"
}

### LOGIN
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "login": "searching",
  "password": "searching"
}

<> 2022-03-12T192426.200.json
<> 2022-03-12T192217.200.json

###
POST http://localhost:8080/user/filter?page=0&size=10&sort=name,desc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjQ3MjU0NTU5LCJleHAiOjE2NDcyNTgxNTksImlzcyI6IlRvcGFsb3EiLCJyb2xlIjoiVVNFUl9ST0xFIn0.TbRB_hlI8Q0tSjOjQLb-zMvweDKCBEKLCHgsLLNggDQ

{
  "fromDate": "2022-03-09"
}

###
POST http://localhost:8080/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjQ3MDk1MDY2LCJleHAiOjE2NDcwOTg2NjYsImlzcyI6IlRvcGFsb3EiLCJyb2xlIjoiVVNFUl9ST0xFIn0.hXsj1iqRh_nDA6zzLugMcKZU8XKRGU4F-dk2t4DWy84

{
  "name": "Rakhimajon",
  "surname": "Kilichbaeva",
  "phone": "9989312345657",
  "login": "r@khima",
  "password": "r@khima",
  "role": "ADMIN_ROLE"
}

<> 2022-03-12T192446.403.txt
<> 2022-03-12T192300.200.json

